import { User } from "./models";

export const users: User[] = [
  { name: 'Tintin', color: 'lightblue' },
  { name: 'Astérix', color: 'gold' },
  { name: 'Corto Maltese', color: 'sienna' },
  { name: 'Doraemon', color: 'dodgerblue' },
  { name: 'Nausicaä', color: 'forestgreen' },
  { name: 'Lupin III', color: 'darkred' },
  { name: 'Aster Blistok', color: 'darkorange' },
  { name: 'Cubitus', color: 'lightseagreen' },
  { name: 'Gaston Lagaffe', color: 'tomato' },
  { name: 'Mafalda', color: 'indigo' },
];

export const textMessages: string[] = [
  "PogChamp",
  "Kappa",
  "LOL",
  "This streamer is a wizard 🧙‍♂️",
  "Press F to pay respects",
  "Did someone say 'Pizza'?",
  "I'm here for the memes!",
  "That's what she said!",
  "Why did the streamer go to the bank? To get their Twitch-ings!",
  "Streamer: *Makes a mistake* Chat: *Spams LULW*",
  "This chat is pure chaos, and I love it!",
  "Chat: *Starts a meme war*",
  "Streamer: *Laughs uncontrollably* Chat: *Spams 'HAHA'",
  "I came for the gameplay, but I stayed for the chat!",
  "Why did the chicken cross the road? To get to the Twitch stream!",
  "Chat: *Pastes ASCII art*",
  "This stream is the highlight of my day!",
  "Streamer: *Facepalms* Chat: *Pastes 'Facepalm' emote*",
  "When in doubt, POG it out!",
  "Chat: *Types 'FOLLOWED'*",
  "This chat is like a box of chocolates; you never know what you're gonna get!",
  "Streamer: *Says 'No spoilers, please'* Chat: *Starts a spoiler spree*",
  "I've got my popcorn ready for this chat!",
  "Streamer: *Sings a song* Chat: *Turns into a choir*",
  "Did you hear about the Twitch chat that won the lottery? They all got Subscribed!",
  "Streamer: *Accidentally goes offline* Chat: *Freaks out and types 'F' for 5 minutes*",
  "Chat: *Spams '420' during a game*",
  "Streamer: *Misses an easy shot* Chat: *Calls them 'KappaRoss'*",
  "This chat is my happy place!",
  "Streamer: *Opens a loot box* Chat: *Expects legendary items*",
  "Chat: *Counts down from 10 to start a hype train*",
  "Streamer: *Asks a question* Chat: *Gives 100 different answers*",
  "I'm convinced this chat is powered by memes!",
  "Streamer: *Streams for 10 hours* Chat: *Says 'I just got here!'*",
  "Streamer: *Wins a game* Chat: *Claims credit for the victory*",
  "Chat: *Turns into a detective to solve in-game mysteries*",
  "Streamer: *Mentions food* Chat: *Lists their favorite dishes*",
  "Streamer: *Takes a break* Chat: *Riot mode activated*",
  "Chat: *Spams 'POGGERS' during intense moments*",
  "This chat has its own language, and I'm learning it!",
];